# Generated by Django 3.2.8 on 2021-11-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=50, verbose_name='Raça')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espaco', models.CharField(max_length=100, verbose_name='Espaço')),
                ('brinquedos', models.CharField(max_length=100)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Higienizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpeza', models.CharField(max_length=100)),
                ('cuidados', models.CharField(max_length=100)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentacao', models.CharField(max_length=100, verbose_name='Tipo de Alimentação')),
                ('racao', models.CharField(max_length=100, verbose_name='Ração')),
                ('quantidade', models.CharField(max_length=100)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.animal')),
            ],
        ),
    ]
